### ISSUE TITLE
Rover Pro /robot_status msg battery info fields missing

### ISSUE THREAD

**Issue by TobyUllrich** [RoverRobotics/roverrobotics_ros1#19]
When using the pro.launch on our rover pro the /robot_status topics is missing many fields and some seem to be wrong

```
layout:
  dim: []
  data_offset: 0
data: [0.0, -860.0, 7.0, 102.0, 0.0, 0.0, -756.0, 16.0, 255.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 64637.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

This is a message during driving backwards. The two drive motor information seems plausible but the battery information seems wrong as the robot was not charging during this and there is no Battery Voltage displayed.

When requesting the robot information on the /robot_unique_info topic the response is the following

```
layout: 
  dim: []
  data_offset: 0
data: [0.0, 10008.0, 0.0, 0.0, 0.0]
```

This rover pro unite was flashed with the supplied firmware flasher before, these events
